services:
  caddy:
    build:
      context: ./caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      DNS_API_TOKEN: ${DNS_API_TOKEN}
    volumes:
      - ./caddy/etc/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./django/staticfiles:/app/staticfiles:ro
      - caddy-data:/data
      - caddy-config:/config
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "8883:8883"
    volumes:
      - ../certs/mosquitto:/mosquitto/certs:ro
      - ./mosquitto/config:/mosquitto/config:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  postgres:
    image: postgres:18
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql

  django-web:
    build:
      context: ./django
    container_name: django-web
    restart: unless-stopped
    volumes:
      - ./django:/app:rw
      - ../certs/devices:/certs/devices:ro
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS} 
    command: python manage.py runserver 0.0.0.0:8000
  
  django-mqtt-catcher:
    build:
      context: ./django
    container_name: django-mqtt-catcher
    restart: unless-stopped
    volumes:
      # Must have the exact same volume mounts as django-web
      - ./django:/app:rw
      - ../certs/devices:/certs/devices:ro
    environment:
      # Must have the exact same environment variables only postgres is used though
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS} 
    command: python manage.py mqtt_catcher

volumes:
  postgres-data:
  mosquitto-data:
  mosquitto-log:
  caddy-data:
  caddy-config: