# Generated by Django 6.0.5 on 2026-05-30 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicemessageraw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicemessageraw',
            options={'ordering': ['received_at'], 'verbose_name': 'Device Message Raw', 'verbose_name_plural': 'Device Messages Raw'},
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='Unnamed Device', max_length=100),
        ),
        migrations.CreateModel(
            name='PumpStateSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('mains_power_present', models.BooleanField()),
                ('pump_relay_active', models.BooleanField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_state_samples', to='devices.device')),
                ('raw_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pump_state_sample', to='devices.devicemessageraw')),
            ],
            options={
                'verbose_name': 'Pump State Sample',
                'verbose_name_plural': 'Pump State Samples',
                'ordering': ['received_at'],
                'indexes': [models.Index(fields=['device', '-received_at'], name='devices_pum_device__7920ef_idx')],
            },
        ),
    ]
