# Generated by Django 6.0.5 on 2026-05-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_devicemessageraw_options_device_device_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_name',
            new_name='name',
        ),
    ]
