# Generated by Django 6.0.5 on 2026-05-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_rename_device_name_device_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemessageraw',
            name='device_timestamp',
        ),
        migrations.AddField(
            model_name='devicemessageraw',
            name='device_unix_time_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
