# Generated by Django 6.0.5 on 2026-05-31 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_devicemessageraw_device_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AlterField(
            model_name='pumpstatesample',
            name='raw_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pump_state_sample', to='devices.devicemessageraw'),
        ),
    ]
